### ISSUE TITLE
PLECS Initialer Induktorstrom

### ISSUE THREAD

**Issue by CurrentCrafter** [sid115/capstone#5]
- `pv_lut.plecs`: Wie speisen wir den Initialstrom $i(t=0)$ aus dem LUT in L_PV ein? Das System ist ohne diesen Strom undefiniert.

**Comment by marrk2** [comment]
Leitungsinduktivität: ca. 1,303 µH/m (Standart Doppelleitung mit 4mm² Leiterquerschnitt, Duchmesser aussen 5,2mm)
Leitungkapazität: 0.291pF/m 
Ohm'scher Widerstand: 5,09 mOhm/m
